### ISSUE TITLE
Strange python errors when working from project directory

### ISSUE THREAD

**Issue by AYEG** [dispel/jak#54]
Hi! Got Jak up and running without any issues on a test directory and it is great! After installing it into an existing project with git, there seems to be some kind of issue with Python. The error shown below also happens with Python 3.6 and when working from within my project folder with Conda virtual environment activated (the python path will also correctly show that (e.g. "/Users/username/miniconda3/envs/project/lib/python3.6/site-packages/jak/) , but the errors message itself remains the same). 

Traceback (most recent call last):
  File "/usr/local/bin/jak", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 722, in call
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/jak/app.py", line 177, in decrypt
    decrypt_inner(all_or_filepath=filepath, key=key, keyfile=keyfile)
  File "/usr/local/lib/python3.7/site-packages/jak/decorators.py", line 47, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/jak/decorators.py", line 61, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/jak/decorators.py", line 72, in wrapper
    result = f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/jak/decorators.py", line 39, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/jak/app.py", line 162, in decrypt_inner
    result = cs.decrypt_file(filepath=filepath, key=key, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/jak/crypto_services.py", line 109, in decrypt_file
    decrypted_secret = aes256_cipher.decrypt(ciphertext=ciphertext)
  File "/usr/local/lib/python3.7/site-packages/jak/aes_cipher.py", line 116, in decrypt
    return self._use_old_decrypt_function(version=version, ciphertext=ciphertext)
  File "/usr/local/lib/python3.7/site-packages/jak/aes_cipher.py", line 107, in _use_old_decrypt_function
    raise Exception('FATAL: No one should end up here.... VERSION: {}, C: {}'.format(version, ciphertext))
Exception: FATAL: No one should end up here.... VERSION: b'6\x8b^\xb0\x83\x0f9', C: b'6\x8b^\xb0\x83\x0f9\x14\xc05?\xbe\xfb\xef\xbe\xfb\xef\xbe\xfb\xef\xbe\xfb\xef\xbe\xfb\xef\xbe\xfb\xef\xbe\xfb\xef\xbe\xfb\xef\xbe\xfb\xef\xbe\xfb\xef\xbe\xfb\xef\xbe\xfb\xe2,4\xe0\xc4\xfc\xf0\x13\x1e\xf6\xab\x89\xa6\xe5z\xc7\xad\xff\xfb!\xa3\x08\x9f\xb1\xeb^r\x1a\r81?<\x04\xc7\xff\xfb\x1e\xb4\xd3\x83\x13\xf3\xc0LsN\x0cO\xcf\x011'

I was able to get a precommit hook to run Jak with NPM without errors when placing a .sh script within node_modules/.bin/.  So the only thing left to do is to reverse things after pushing to git. 

What might be causing this error? 
Thanks

**Comment by chrisdl** [comment]
Hey @AYEG,

Sorry to see you were having issues. I can dig into this, but since you closed the issue I'm guessing you figured it out? If so, I would love to know what happened so I can decide if there is something I can do to prevent people from having the same issue as you had.

**Comment by AYEG** [comment]
Hi! I installed jak in two places and also tried to hook it into npm pre-commit (which in hindsight is not needed at all) and it became a bit confusing. I thought there was something wrong with the python interpreter it was using. this errors generally shows up when I try to decrypt something that is already decrypted, it's likely that this was the main cause. In the end I just made sure I was working with Jak from within that project folder and run the commands in terminal before git commit&add and after git push and now it seems to work reliably.

**Comment by chrisdl** [comment]
Ah I see an issue actually!

Right now jak assumes a file is decrypted it if throws an error on removing the base64 encoding. But this does not always happen so for some files you will see the "file already decrypted"-message but for some you get the error you saw, which is not what a human should be reading. 

```python
try:
        ciphertext = base64.urlsafe_b64decode(ciphertext_no_header)
    except (TypeError, binascii.Error):
        return 'The file "{}" is already decrypted, or is not in a format I recognize.'.format(
            filepath)
```

I'll reopen this issue and improve "already decrypted" checking. thanks!
